<Tab_company>:
    title:'Company'
    md_bg_color:app.theme_cls.primary_light
    MDBoxLayout:
        MDBoxLayout:
            orientation:'vertical'
            size_hint_x:.6
            padding:"10dp"
            spacing:'10dp'
            md_bg_color:app.theme_cls.primary_dark
            MDLabel:
                text:"Regsistor Company"
                halign:'center'
                bold:True
                font_size:'30sp'
                color:app.theme_cls.opposite_bg_normal